### ISSUE TITLE
Tags Feature

### ISSUE THREAD

**Issue by Zynde** [mariodavid/cuba-component-attachable#1]
As a feature it would be nice to be able to add TAGS to files. Perhaps with the TokenList as the control for this. 

Tags would help with searching and grouping.

**Comment by mariodavid** [comment]
Hi, thanks for the suggestion.

Adding tags to attachments would not be a big problem. However: filtering attachments is currently not possible due to implementation issues (this is why the generic filter component is not used in the attachable-browse.xml screen). Would need to take a deeper look into it.

**Comment by mariodavid** [comment]
another a little more strict possibility would be to create a `AttachmentCategory` which is just a entity that can be selected for categorizing attachments. Grouping would also easily work due to the grouping facility of the table.

**Comment by mariodavid** [comment]
Done in #7
